### PR TITLE
prevent get siblings if no male and female parents

### LINKED ISSUE #2052: Brapi response in sweetpotatobase to call: germplasm/id/pedigree
Expected Behavior 
--------------------------------------------------------------------------

When pedigree is 'unknown' or parents id is 'null' then no siblings should be returned.

For Bugs:
---------

### Environment 

web and R client

#### Steps to Reproduce

 https://sweetpotatobase.org/brapi/v1/germplasm/103412/pedigree

### PR DESCRIPTION
**Pull request by nickmorales**
Description 
-----------------------------------------------------
Prevents brapi pedigree from fetching siblings if there are no female and male parents.
@dauglyon will speed up the pedigree search

closes #2052 

Checklist 
---------------------------------------------------------------------------------------
- [ ] Refactoring only
- [ ] Documentation only
- [ ] Fixture update only
- [x] Bug fix
  - [x] The relevant issue has been closed.
  - [ ] Further work is required.
- [ ] New feature
  - [ ] Relevant tests have been created and run.
  - [ ] Data was added to the fixture
    - [ ] Data was added via a patch in `/t/data/fixture/patches/`.
  - [ ] User-Facing Change
    - [ ] The user manual in `/docs` has been updated.
  - [ ] Any new Perl has been documented using **perldoc**.
  - [ ] Any new JavaScript has been documented using **JSDoc**.

### CODE REVIEW

File: lib/CXGN/BrAPI/v1/Germplasm.pm [hunk 1]
```diff
@@ -253,16 +253,18 @@ sub germplasm_pedigree {
...
-        #print STDERR Dumper $progenies;
         my @siblings;
-        foreach (@$progenies){
-            if ($_->[5] ne $uniquename){
-                my $germplasm_id = $_->[4];
-                push @siblings, {
-                    germplasmDbId => qq|$germplasm_id|,
-                    defaultDisplayName => $_->[5]
-                };
+        if ($female_name && $male_name){
```
Comment (dauglyon) [inline lib/CXGN/BrAPI/v1/Germplasm.pm]: Should it be `if ($female_name || $male_name){`? This looks like it won't search unless it has both parents stored, but we still want to return if we only have one.

Comment (nickmorales) [reply lib/CXGN/BrAPI/v1/Germplasm.pm]: 👍
