### PR TITLE
Topic/smtp with auth

### LINKED ISSUE #2717: Issues with account confirmation emails
Expected Behavior 
--------------------------------------------------------------------------
Account confirmation emails have been failing in the latest docker container with error
`CXGN::Contact: UNABLE TO SEND EMAIL NOTIFICATION`
No other details to help troubleshoot. I added smtp conf variables and tried switching to using an external smtp server, but ran into various AUTH errors in the Mail::Sendmail package.

For Bugs:
---------

### PR DESCRIPTION
**Pull request by bellerbrock**
Description 
-----------------------------------------------------
closes #2717

Checklist 
---------------------------------------------------------------------------------------
- [ ] Refactoring only
- [ ] Documentation only
- [ ] Fixture update only
- [x] Bug fix
  - [ ] The relevant issue has been closed.
  - [ ] Further work is required.
- [ ] New feature
  - [ ] Relevant tests have been created and run.
  - [ ] Data was added to the fixture
    - [ ] Data was added via a patch in `/t/data/fixture/patches/`.
  - [ ] User-Facing Change
    - [ ] The user manual in `/docs` has been updated.
  - [ ] Any new Perl has been documented using **perldoc**.
  - [ ] Any new JavaScript has been documented using **JSDoc**.
  - [ ] Any new _legacy_ JavaScript has been moved from `/js` to `/js/source/legacy`.

### CODE REVIEW

File: lib/CXGN/Contact.pm [hunk 1]
```diff
@@ -76,48 +77,58 @@ sub send_email {
...
-                };
-            }
 
-            if ( sendmail(%mail) ) {
-                print STDERR
-"CXGN::Contact: Email notification sent from $mailfrom to $mailto.\n";
-            }
-            else {
-                print STDERR "CXGN::Contact: UNABLE TO SEND EMAIL NOTIFICATION\n";
+              my ($mail,$error) = Email::Send::SMTP::Gmail->new(
```
Comment (nickmorales) [inline lib/CXGN/Contact.pm]: @bellerbrock can you please add this into the Build.Pl and also add it as a dependency for the breedbase_docker?

Comment (bellerbrock) [reply lib/CXGN/Contact.pm]: GC, no problem
