### PR TITLE
NIRS model saving fix

### LINKED ISSUE #3160: NIRS tool is not saving the training model
Expected Behavior 
--------------------------------------------------------------------------

The NIRs tool on cassavabase can generate but not saving the model. 

For Bugs:
---------

### PR DESCRIPTION
**Pull request by nickmorales**
Description 
-----------------------------------------------------
Check analysis name to fix a rare bug

closes #3160

Checklist 
---------------------------------------------------------------------------------------
- [ ] Refactoring only
- [ ] Documentation only
- [ ] Fixture update only
- [ ] Bug fix
  - [ ] The relevant issue has been closed.
  - [ ] Further work is required.
- [ ] New feature
  - [ ] Relevant tests have been created and run.
  - [ ] Data was added to the fixture
    - [ ] Data was added via a patch in `/t/data/fixture/patches/`.
  - [ ] User-Facing Change
    - [ ] The user manual in `/docs` has been updated.
  - [ ] Any new Perl has been documented using **perldoc**.
  - [ ] Any new JavaScript has been documented using **JSDoc**.
  - [ ] Any new _legacy_ JavaScript has been moved from `/js` to `/js/source/legacy`.

### CODE REVIEW

**Review by lukasmueller — APPROVED** [review]
:-)

File: lib/CXGN/Analysis/AnalysisCreate.pm [hunk 1]
```diff
@@ -365,6 +365,10 @@ sub store {
     print STDERR Dumper $analysis_model_type;
     my $model_type_cvterm_id = SGN::Model::Cvterm->get_cvterm_row($bcs_schema, $analysis_model_type, 'protocol_type')->cvterm_id();
 
+    if ($analysis_to_save_boolean eq 'yes' && !$analysis_name) {
```
Comment (lukasmueller) [inline lib/CXGN/Analysis/AnalysisCreate.pm:368]: shouldn't this be 
if ( ($analysis_to_save_boolean eq 'yes') && !$analysis_name) { 
(the first comparison needs parentheses)

Comment (lukasmueller) [reply lib/CXGN/Analysis/AnalysisCreate.pm:368]: Verified the precedence and this should be ok :-)

**Review by lukasmueller — APPROVED** [review]
:-)
