### PR TITLE
Topic/fix downloadgbs

### LINKED ISSUE #363: match accession names, protocol versions to GBS download output header
In "Manage" -> "Download" -> " Download GBS Genotype"
Using a list of accessions, the download function does find GBS data related to individuals but accession names do not match their related GBS data column.
1- In the download output file, accession name order of the columns is identical to the input list but not to the data columns.
2- Download function  output does include all available GBS versions available, without specifying it abd adding extra accession headers for it. Multiple versions can not be distinguished.

#list name order: CR15B3	CW48216	CW3514	CW45036	TMS30555	TMEB419	TMEB778	TMS010040	TMS980505	NR110080	TMS972205
#actual name order:
TMEB419	NR110080	CR15B3	TMEB778	CW45036	TMEB778	TMEB778	TMEB419	TMEB419	TMEB419	TMEB419	CW48216	TMS010040	TMS980505	TMEB419	TMS980505

Attached an example
[genotyping_dowload_error.xlsx](https://github.com/solgenomics/sgn/files/65908/genotyping_dowload_error.xlsx)

### PR DESCRIPTION
**Pull request by bellerbrock**
closes #363 and #364

### CODE REVIEW

File: lib/SGN/Controller/BreedersToolbox/Download.pm [hunk 1]
```diff
@@ -23,6 +23,7 @@ use CXGN::List::Transform;
 use Spreadsheet::WriteExcel;
 use CXGN::Trial::Download;
 use POSIX qw(strftime);
+use Sort::Versions;
```
Comment (nickmorales) [inline lib/SGN/Controller/BreedersToolbox/Download.pm]: this needs to be installed on machines using: sudo cpanm install Sort::Versions
